### ISSUE TITLE
【依頼】フリマアプリの挙動確認

### ISSUE THREAD

**Issue by Takashi-Na** [Takashi-Na/furima_28780#9]
#### 本番環境のURL
https://furima-28780.herokuapp.com/

#### Basic認証
ID:admin
Password:3333

#### 出品者
Email:test@test.jp
Password:12345a

#### 購入者
Email:test2@test.jp
Password:12345a

#### 購入用カード
カード番号:4242424242424242
期限:3/23
セキュリティーコード:123

**Comment by tnk1215** [comment]
Takashi-Naさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①　商品詳細ページにおいて出品時に登録した「商品の説明」が表示されていない**
商品詳細機能の「商品出品時に登録した情報が見られるようになっている」という条件に外れてしまいます。
詳細ページで商品の説明も表示されるように修正しましょう！

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Takashi-Na** [comment]
**①商品詳細ページにおいて出品時に登録した「商品の説明」が表示されていない**

について、実装が抜けていました。すみません。
修正しましたのでよろしくお願いします。

**Comment by airraid714** [comment]
Takashi-Naさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
①ユーザー新規登録
"必須項目を入力し、ユーザーの登録ができる。
必須項目が一つでも欠けているとユーザー登録ができない。
・パスワード
    パスワードは7文字以上で、確認用を含めて2回入力できる
⇨6文字から可能になっています。

以下ユーザー新規登録時に入力するところが見られませんでした。
（※「・メアド・名前などでユーザー登録 ▶ マイページにいき、住所などの登録が可能」という実装は要件を満たしていないため注意してください） 

・送付先氏名
    送付先氏名が、それぞれ名字と名前で入力できる
・送付先氏名のふりがな
    送付先氏名のふりがなが、それぞれ名字と名前で入力できる
・郵便番号
・都道府県
・市区町村
・番地"

②マイページボタンを押しても反応がない。⇨マイページの確認が出来ませんでした。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by airraid714** [comment]
Takashi-Naさん
大変失礼しました。先程の挙動確認の際誤ったリストにて確認してしまいましたので訂正いたします。
申し訳ございませんでした！
再度挙動確認をいたしますので、お待ちいただきたいです。

**Comment by Takashi-Na** [comment]
了解しました！
お待ちしています。

**Comment by airraid714** [comment]
Takashi-Naさん、先程は大変失礼致しました。
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
①　商品編集画面にて、商品情報の変更を行いましたが変更されないままになっております。
　商品編集機能において、「商品情報（商品画像・商品名・商品の状態など）を変更できる」
の要件から外れてしまいますので、編集した情報が正しく保存されるようにしましょう！

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Takashi-Na** [comment]
①「商品情報（商品画像・商品名・商品の状態など）を変更できる」
について、確認・修正を行いました。
ご確認をお願いします。

**Comment by oshim0115** [comment]
高橋さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。**
